### ISSUE TITLE
Confused About `delta` in Week4, question 8

### ISSUE THREAD

**Issue by chrjx** [alfredcai/Coursera-Computational-NeuroScience#3]
https://github.com/alfredcai/Coursera-Computational-NeuroScience/blob/fa8e2df876c8327712f734887631e5eb8f32f664/Week-4/Quiz/Programming/Python/tuning3.py#L46

你好，这个repo很有帮助，非常感谢！

在第四周的第8题，我想请教一下 `delta` 的是什么，为什么要计算 `delta`。

谢谢🙏

**Comment by alfredcai** [comment]
E(ax) = aE(x), Var(aX) = a^2 Var(x). 柏松分布的性质，E[x]=Var(x). a=10.  ==> aE(x) = a^2Var(x) => 0 = 10*Var(x)-E(x)

**Comment by chrjx** [comment]
很有帮助，感谢🙏
